<?php
require_once('includes.php');
$pageTitle = 'Page Builder';
require_once('./../page-head.php');
?>

<body class="d-flex flex-column vh-100 mesh-gradient overflow-y-auto">
  <?php
  try {
    $successAlert = (new NodeInline)
      ->setClass('alert', 'alert-success', 'alert-dismissible')
      ->setAttribute('role', 'alert')
      ->addChild((new NodeInline('strong'))->addChild('Success: '))
      ->addChild('Page has been created successfully')
      ->addChild((new NodeInline('button'))
        ->setClass('btn-close')
        ->setAttribute('data-bs-dismiss', 'alert')
        ->setAttribute('aria-label', 'Close'));

    $logo = (new NodeInline('a'))
      ->setClass('navbar-brand', 'd-inline-flex', 'align-items-center', 'gap-2')
      ->setAttribute('href', '#')
      ->addChild((new NodeInline('img', false))
        ->setAttribute('src', 'https://getbootstrap.com//docs/5.3/assets/brand/bootstrap-logo.svg')
        ->setAttribute('alt', 'Bootstrap Logo')
        ->setAttribute('height', '30'))
      ->addChild('Page Builder');

    $nav = (new NodeList)
      ->setClass('nav', 'nav-underline')
      ->addChild((new NodeListItem)
        ->setClass('nav-item')
        ->addChild((new NodeInline('a'))
            ->setClass('nav-link', 'active')
            ->setAttribute('aria-current', 'true')
            ->setAttribute('href', '#')
            ->addChild('Active Link')
        ))
      ->addChild((new NodeListItem)
        ->setClass('nav-item')
        ->addChild((new NodeInline('a'))
            ->setClass('nav-link')
            ->setAttribute('href', '#')
            ->addChild('Normal Link')
        ))
      ->addChild((new NodeListItem)
        ->setClass('nav-item')
        ->addChild((new NodeInline('a'))
            ->setClass('nav-link', 'disabled')
            ->setAttribute('aria-disabled', 'true')
            ->addChild('Disabled Link')
        ));

    $searchForm = (new NodeBlock('form'))
      ->setAttribute('role', 'search')
      ->addChild((new NodeInput('page-search', 'search', placeholder: 'Search anything...'))
        ->setClass('form-control')
        ->setAttribute('aria-label', 'Search'));

    $header = (new NodeBlock('header'))
      ->setClass('card-header', 'navbar')
      ->addChild($logo)
      ->addChild($nav)
      ->addChild($searchForm);

    $leftSection = (new NodeBlock('section'))
      ->setClass('col-12', 'col-lg-6', 'text-center')
      ->addChild($successAlert)
      ->addChild((new NodeBlock('h1'))
        ->addChild('👋 Welcome to Page Builder!')
        ->setClass('mt-5'))
      ->addChild((new NodeBlock('p'))
        ->setClass('lead', 'mb-4')
        ->addChild('This is an example of a page generated by PHP custom classes.'))
      ->addChild((new NodeInline('a'))
        ->setClass('btn', 'btn-success', 'bg-gradient', 'px-4', 'fw-medium')->addChild('View Generated Code')
        ->setAttribute('href', 'generated-code-view.php')
        ->setAttribute('target', '_blank'));

    $nameInput = new NodeInput(
      name: 'name',
      placeholder: 'John Doe',
      label: (new NodeInputLabel(text: 'Name'))->setClass('form-label'),
    );
    $nameInput->setClass('form-control');

    $emailInput = new NodeInput(
      name: 'email',
      type: 'email',
      placeholder: 'johndoe@gmail.com',
      required: true,
      label: (new NodeInputLabel(text: 'Email Address'))->setClass('form-label'),
      errorMessage: 'Email is required'
    );
    $emailInput->setClass('form-control');

    $textArea = new NodeTextArea(
      name: 'message',
      placeholder: 'Describe your issue...',
      required: true,
      label: (new NodeInputLabel(text: 'Message'))->setClass('form-label'),
      errorMessage: 'Message is required'
    );
    $textArea->setClass('form-control');

    $submitBtn = (new NodeInput(
      type: 'submit',
      value: 'Submit Form Data',
    ))->setClass('btn', 'btn-primary', 'bg-gradient', 'px-4', 'fw-medium', 'mt-3');

    $form = (new NodeBlock('form'))
      ->setClass('needs-validation', 'row', 'g-3', 'align-items-center', 'justify-content-center', 'pt-3')
      ->setAttribute('novalidate')
      ->addChild((new NodeBlock)
        ->setClass('col-sm')
        ->addChild($nameInput->getLabel())
        ->addChild($nameInput))
      ->addChild((new NodeBlock)
        ->setClass('col-sm')
        ->addChild($emailInput->getLabel())
        ->addChild($emailInput)
        ->addChild($emailInput->getErrorMessage()))
      ->addChild((new NodeBlock)
        ->setClass('col-12')
        ->addChild($textArea->getLabel())
        ->addChild($textArea)
        ->addChild($textArea->getErrorMessage()))
      ->addChild((new NodeBlock)
        ->setClass('col-auto')
        ->addChild($submitBtn));

    $rightSection = (new NodeBlock('section'))
      ->setClass('col-12', 'col-md-8', 'col-lg-5')
      ->addChild((new NodeBlock('h2'))->addChild('Contact Form'))
      ->addChild($form);

    $main = (new NodeBlock('main'))
      ->setClass('card-body', 'row', 'h-100', 'align-items-center', 'justify-content-evenly', 'overflow-y-auto')
      ->addChild($leftSection)
      ->addChild($rightSection);

    $pageHTML = (new NodeBlock)
      ->setClass('container-lg', 'py-3', 'h-100')
      ->addChild((new NodeBlock)
        ->setClass('card', 'h-100', 'shadow-lg')
        ->addChild($header)
        ->addChild($main))
      ->render();

    echo $pageHTML;
    file_put_contents('generated-code.html', $pageHTML);
  } catch (Exception $e) {
    echo (new NodeInline)
      ->setClass('alert', 'alert-danger')
      ->addChild((new NodeInline('strong'))->addChild('Error: '))
      ->addChild($e->getMessage())
      ->render();
  }

  ?>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script>
    const forms = document.querySelectorAll('.needs-validation')
    Array.from(forms).forEach(form => {
      form.addEventListener('submit', event => {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }
        form.classList.add('was-validated')
      }, false)
    })
  </script>
</body>

</html>